spring.application.name = mycoolapp

# Configure my props
my.firstname = Yong
my.lastname = Yangyuen
learning.topic = 17-crud-student

# Configure info & health-check monitoring
# Use Wildcard "*" to expose all endpoints
management.endpoints.web.exposure.include = *
#management.endpoints.web.exposure.exclude = health, info
management.info.env.enabled = true
spring.security.user.name = admin
spring.security.user.password = admin

info.app.name = My Super Cool App
info.app.description = A crazy and fun app, yoohoo!
info.app.version = 1.0.0
info.app.owner = Mr. Yong Yangyuen

# Change Spring Boot embedded server port
server.port = 6969

# Set the context path of the application
server.servlet.context-path = /mycoolapp

# Enable @Lazy for global (Applying @Lazy to all Bean)
#spring.main.lazy-initialization = true

spring.datasource.url = jdbc:mysql://localhost:3307/student_tracker
spring.datasource.username = springstudent
spring.datasource.password = springstudent

# Turn off the Spring Boot banner
spring.main.banner-mode = off

# Reduce logging level by setting logging level to warn
# Ex. value: trace, debug, info, warn, error, fatal, off
# For ex. if you set logging.level.root to "warn", log will be shown only "warn", "error", "fatal" (left to right in above comment)
logging.level.root = warn

spring.jpa.open-in-view = off

# Add logging configs to display SQL statements
logging.level.org.hibernate.SQL = debug
logging.level.org.hibernate.orm.jdbc.bind = trace

# Configure JPA/Hibernate to auto create the tables.
# the "create" config will not keep existing data in the tables.
# the "update" config will keep existing data in the tables.
# For testing only, not use this on Production environment because all data in the table will be deleted (the table is dropped).
spring.jpa.hibernate.ddl-auto = update
